export default { 
	data: [ { 
		title: "Studying Computer Science",
 short: "Bsc of Computer Science",
 		date: "2021-2024",
 		width: '204px',
 		clickable: true,
 		info: `This course has taught me a wide range
		 of programming languages, frameworks, all kinds of calculus and algorithms, 
		 but most importantly, it made me develop a problem-solving mindset 
		 and a passion for Data Science and Machine Learning, a field I will explore further 
		 on my master's degree. I have developed multiple projects some of them available on my Github.`,
 		location: "Lisbon, Portugal",
 		at: "Instituto Superior Técnico",
 type: "edu",
 	image: "",	
 	color: '#E9F4ED', left:false, },
 { 
		title: "Finished Short Course: 'Product and Process Design' ",
 short: "Product and Process Design course",
 		date: "2023",
 		width: '215px',
 		clickable: true,
 		info: `Took a 1 week course in Delft where I collaborated with 4 people from
		 different nationalities to come up with a solution to a specific problem
		 regarding the heating of a neighborhood in Breda, Netherlands. Here I learned
		 how to work in a team with people from different backgrounds and cultures, 
		 and most importantly, how to come up with a solution to a problem in a short period of time.`,
 		location: "Netherlands",
 		at: "Delft University of Technology",
 type: "edu",
 	image: "",	
 	color: '#DFF1E5', left:true, },
 { 
		title: "Participated in the ETHGlobal Hackathon",
 short: "ETHGlobal Hackathon",
 		date: "2023",
 		width: '215px',
 		clickable: true,
 		info: `Together with four colleagues developed a Web3 website using Ethereum's blockchain technology. Implemented smart 
		contracts with Solidity and used React for the front-end. The project was an online forum, allowing users to post and comment on topics,
 with the added feature of tipping other users with Ethereum. More on the project can be found `,
 		location: "Lisbon, Portugal", at:"",
 type: "xp",
 	image: "",	
 	color: '#DFF1E5', left:true, },
 { 
		title: "Developed first website with React",
 short: "First Website",
 		date: "2023",
 		width: '215px',
 		clickable: true,
 		info: `Developed a website to practice my then new skills in React and web development. 
		The website is a minimalist blackjack emulator online game that resorts to a public API
		 to fetch cards. `,
 		location: "Lisbon, Portugal", at:"Home",
 type: "xp",
 	image: "",	
 	color: '#D7ECDE', left:false, },
 { 
		title: "Finished 1 week course: 'Architectural Heritage' ",
 short: "Architectural Heritage course",
 		date: "2023",
 		width: '220px',
 		clickable: true,
 		info: `Took a 1 week course in Milan where together with more colleagues
		 we analyzed the structural integrity of historical buildings. Despite the demanding nature of the program, which required a solid
		  foundation in architecture, I managed to model how historical buildings endure over time. I analyzed factors like ground motion and wind force
		   to predict their impact on structural integrity. This insight helped the professors plan better maintenance strategies for the long term. Finished with the
		   maximum score of A.
		 `,
 		location: "Italy",
 		at: "Politecnico di Milano",
 type: "edu",
 	image: "",	
 	color: '#CCE4D4', left:false, },
 { 
		title: "Volunteered as a mentor for new students",
 short: "",
 		date: "2022-2023",
 		width: '210px',
 		clickable: false,
 		info: ``,
 		location: "Lisbon, Portugal",
 		at: "Instituto Superior Técnico",
 type: "xp",
 	image: "",	
 	color: '#C5E0CE',
 		left: true, },
 { 
		title: "Coached younger Roller Hockey goalkeepers",
 short: "",
 		date: "2022-2023",
 		width: '200px',
 		clickable: false,
 		info: ``,
 		location: "Lisbon, Portugal",
 		at: "APAC Tojal",
 type: "xp",
 	image: "",	
 	color: '#C5E0CE',
 		left: false, },
 { 
		title: "Picked up the guitar for the first time",
 short: "",
 		date: "2022",
 		width: '200px',
 		clickable: false,
 		info: ``,
 		location: "Lisbon, Portugal", at:"Home",
 type: "xp",
 	image: "",	
 	color: '#B9D3C2',
 		left: true, },
 { 
		title: "Finished 'Physical Computing based on Open Software and Hardware Platforms' course",
 short: "Physical Computing course",
 		date: "2022",
 		width: '200px',
 		clickable: true,
 		info: `Engineered, with a colleague, a system to monitor classroom occupancy. The system, composed of locally installed devices, each containing an Arduino board with sensors, could calculate the number of people inside a room and then output that information into a website available to everyone. 
		 This innovative solution not only improves students' ability to make informed decisions by identifying less crowded study spaces but also contributes to optimizing the overall availability of study rooms across the campus.
		 `,
 		location: "Spain",
 		at: "Universidad Politécnica de Madrid",
 type: "edu",
 	image: "",	
 	color: '#BBD8C5',
 		left: false, },
 { 
		title: "Joined Game Development Club",
 short: "",
 		date: "2022",
 		width: '210px',
 		clickable: false,
 		info: ``,
 		location: "Lisbon, Portugal",
 		at: "Instituto Superior Técnico",
 type: "xp",
 	image: "",	
 	color: '#A1CDAF',
 		left: true, },
 { 
		title: "Finished secondary school",
 short: "",
 		date: "2021",
 		width: '205px',
 		clickable: false,
 		info: ``,
 		location: "Lisbon, Portugal",
 		at: "Escola Dr. Antonio Carvalho Figueiredo",
 type: "edu",
 	image: "",	
 	color: '#97C3A5',
 		left: false, },
 { 
		title: "Volunteered at a local animal shelter",
 short: "",
 		date: "2018",
 		width: '184px',
 		clickable: false,
 		info: ``,
 		location: "Lisbon, Portugal",
 		at: "Chão dos Bichos",
 type: "xp",
 	image: "",	
 	color: '#81C597',
 		left: false, },
 { 
		title: "Volunteered at Food Bank",
 short: "",
 		date: "2017",
 		width: '210px',
 		clickable: false,
 		info: ``,
 		location: "Lisbon, Portugal",
 		at: "Banco Alimentar",
 type: "xp",
 	image: "",	
 	color: '#89C69D',
 		left: true, },
 { 
		title: "Began playing tennis",
 short: "",
 		date: "2009",
 		width: '240px',
 		clickable: false,
 		info: ``,
 		location: "Lisbon, Portugal", at:"",
 type: "xp",
 	image: "",	
 	color: '#71BA89',
 		left: true, },
 { 
		title: "Began playing Roller Hockey",
 short: "Roller Hockey",
 		date: "2008",
 		width: '195px',
 		clickable: true,
 		info: `Hockey has long been a significant part of my life. Playing as a goalkeeper,
 has taught me the importance of responsibility,
 leadership,and teamwork. I have also learned to manage stress and pressure on the most difficult moments. Throughout the years,
 all the effort and dedication got me multiple titles and the possibility to be part of the Under14 National Hockey Team.`,
 		location: "Lisbon, Portugal",
 		at: "APAC Tojal",
 type: "xp",
 	image: "",	
 	color: '#5CBF7D',
 		left: false, },
 ] }