export default { 
	data: [ { 
		title: "Studying Computer Science",
 short: "Computer Science",
 		date: "2021-2024",
 		width: '204px',
 		clickable: true,
 		info: `In this course,
 I learnt multiple concepts,
 from programming languages and frameworks to algorithms and calculus but most importantly,
 I developed a problem-solving mindset and a passion for Data Science and Machine Learning,
 a field I will now pursue for my masters.`,
 		location: "Lisbon, Portugal",
 		at: "Instituto Superior Técnico",
 type: "edu",
 		color: '#E9F4ED', left:false, },
 { 
		title: "Finished 'Product and Process Design' course ",
 short: "Product and Process Design course",
 		date: "2023",
 		width: '215px',
 		clickable: true,
 		info: `Designed and engineered a solution to a specific problem regarding the heating of a neighborhood in Breda,
 Netherlands. The curriculum emphasized the importance of ideation,
 fostering creativity through design thinking,
 and encouraging collaboration with individuals from diverse nationalities. `,
 		location: "Netherlands",
 		at: "Delft University of Technology",
 type: "edu",
 		color: '#DFF1E5', left:true, },
 { 
		title: "Participated in the ETHGlobal Hackathon",
 short: "ETHGlobal Hackathon",
 		date: "2023",
 		width: '215px',
 		clickable: true,
 		info: `Collaborated with four colleagues to construct a Web3 website using Ethereum's blockchain technology. Implemented smart contracts with Solidity and used utilized React for the front-end. The project was an online forum,
 allowing users to post and comment on topics,
 with the added feature of tipping other users with Ethereum.`,
 		location: "Lisbon, Portugal", at:"",
 type: "xp",
 		color: '#DFF1E5', left:true, },
 { 
		title: "Developed first website with React",
 short: "First Website",
 		date: "2023",
 		width: '215px',
 		clickable: true,
 		info: `Developed a website to practice my then new skills in React and web development. The website is a minimalist blackjack emulator online game that resorts to a public API to simulate a deck of cards. You can give it a try here:`,
 		location: "Lisbon, Portugal", at:"Home",
 type: "xp",
 		color: '#D7ECDE', left:false, },
 { 
		title: "Finished 'Architectural Heritage' course ",
 short: "Architectural Heritage course",
 		date: "2023",
 		width: '220px',
 		clickable: true,
 		info: `This course might stand out in my CV as it is a domain vastly different from the field I am pursuing. The truth is I have always had a deep interest for architecture,
 so i chose to do it out of curiosity,
 mainly. Despite the demanding nature of the program,
 which required substantial prior knowledge in the subject,
 something I did not have,
 my work ethic, adaptability,
 and rapid learning skills were pivotal in overcoming the difficulty,
 ultimately resulting in a successful completion with an outstanding grade of A.`,
 		location: "Italy",
 		at: "Politecnico di Milano",
 type: "edu",
 		color: '#CCE4D4', left:false, },
 { 
		title: "Volunteered as a mentor for new students",
 short: "",
 		date: "2022-2023",
 		width: '210px',
 		clickable: false,
 		info: ``,
 		location: "Lisbon, Portugal",
 		at: "Instituto Superior Técnico",
 type: "xp",
 		color: '#C5E0CE',
 		left: true, },
 { 
		title: "Coached younger Roller Hockey goalkeepers",
 short: "",
 		date: "2022-2023",
 		width: '200px',
 		clickable: false,
 		info: ``,
 		location: "Lisbon, Portugal",
 		at: "APAC Tojal",
 type: "xp",
 		color: '#C5E0CE',
 		left: false, },
 { 
		title: "Picked up the guitar for the first time",
 short: "",
 		date: "2022",
 		width: '200px',
 		clickable: false,
 		info: ``,
 		location: "Lisbon, Portugal", at:"Home",
 type: "xp",
 		color: '#B9D3C2',
 		left: true, },
 { 
		title: "Finished 'Physical Computing based on Open Software and Hardware Platforms' course",
 short: "Physical Computing course",
 		date: "2022",
 		width: '200px',
 		clickable: true,
 		info: ` Designed a project to monitor classroom occupancy using open-source technologies. Using sensors and an Arduino board,
 I developed a device that tracks the number of students in each room and created a website to display real time information on the occupancy of each room,
 provided by each device. This innovative solution not only improves students' ability to make informed decisions by identifying less crowded study spaces but also contributes to optimizing the overall availability of study rooms across the campus.`,
 		location: "Spain",
 		at: "Universidad Politécnica de Madrid",
 type: "edu",
 		color: '#BBD8C5',
 		left: false, },
 { 
		title: "Joined Game Development Club",
 short: "",
 		date: "2022",
 		width: '210px',
 		clickable: false,
 		info: ``,
 		location: "Lisbon, Portugal",
 		at: "Instituto Superior Técnico",
 type: "xp",
 		color: '#A1CDAF',
 		left: true, },
 { 
		title: "Finished secondary school",
 short: "",
 		date: "2021",
 		width: '205px',
 		clickable: false,
 		info: ``,
 		location: "Lisbon, Portugal",
 		at: "Escola Dr. Antonio Carvalho Figueiredo",
 type: "edu",
 		color: '#97C3A5',
 		left: false, },
 { 
		title: "Volunteered at a local animal shelter",
 short: "",
 		date: "2018",
 		width: '184px',
 		clickable: false,
 		info: ``,
 		location: "Lisbon, Portugal",
 		at: "Chão dos Bichos",
 type: "xp",
 		color: '#81C597',
 		left: false, },
 { 
		title: "Volunteered at Food Bank",
 short: "",
 		date: "2017",
 		width: '210px',
 		clickable: false,
 		info: ``,
 		location: "Lisbon, Portugal",
 		at: "Banco Alimentar",
 type: "xp",
 		color: '#89C69D',
 		left: true, },
 { 
		title: "Began playing tennis",
 short: "",
 		date: "2009",
 		width: '240px',
 		clickable: false,
 		info: ``,
 		location: "Lisbon, Portugal", at:"",
 type: "xp",
 		color: '#71BA89',
 		left: true, },
 { 
		title: "Began playing Roller Hockey",
 short: "Roller Hockey",
 		date: "2008",
 		width: '195px',
 		clickable: true,
 		info: `Hockey has long been a significant part of my life. Playing as a goalkeeper,
 has taught me the importance of responsibility,
 leadership,and teamwork. I have also learned to manage stress and pressure on the most difficult moments. Throughout the years,
 all the effort and dedication got me multiple titles and the possibility to be part of the Under14 National Hockey Team. `,
 		location: "Lisbon, Portugal",
 		at: "APAC Tojal",
 type: "xp",
 		color: '#5CBF7D',
 		left: false, },
 ] }